name: Hileyi Derle
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java Hazirla (Java 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Yetki Ver
        run: chmod +x gradlew

      - name: Modu Derle
        run: ./gradlew build

      - name: Dosyayi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Minecraft-1-20-6-Hilen
          path: build/libs/*.jar
